class_name TestLifecycleSimulation
extends RefCounted

static func run() -> void:
	_test_time_and_age(); _test_relationships(); _test_breeding_birth_and_persistence(); _test_wool_and_shearing(); _test_large_jump()
static func _test_time_and_age() -> void:
	var clock := GameClock.new(); assert(clock.get_current_time().get_day() == 1); assert(not clock.advance_minutes(-1)); assert(clock.advance_days(1) and clock.get_total_minutes() == 1440 and clock.get_current_time().get_day() == 2); assert(clock.advance_hours(1) and clock.get_total_minutes() == 1500)
	var repository := FlockRepository.new(); var sheep := _sheep("age", SheepRecord.Sex.FEMALE, SheepRecord.AgeStage.LAMB); assert(repository.add_sheep(sheep)); var service := LifecycleService.new(repository)
	var boundaries := [[0,SheepRecord.AgeStage.LAMB],[7*1440-1,SheepRecord.AgeStage.LAMB],[7*1440,SheepRecord.AgeStage.JUVENILE],[14*1440-1,SheepRecord.AgeStage.JUVENILE],[14*1440,SheepRecord.AgeStage.ADULT],[90*1440-1,SheepRecord.AgeStage.ADULT],[90*1440,SheepRecord.AgeStage.ELDER]]
	for boundary: Array in boundaries: assert(service.resolve_age_stage(sheep, GameTime.new(boundary[0])) == boundary[1])
static func _test_relationships() -> void:
	var repo := FlockRepository.new(); var parent := _sheep("p", SheepRecord.Sex.FEMALE); var other := _sheep("o", SheepRecord.Sex.MALE); var child := _sheep("c", SheepRecord.Sex.FEMALE); child.mother_id = "p"; child.father_id = "o"; child.generation = 1; var sibling := _sheep("s", SheepRecord.Sex.MALE); sibling.mother_id = "p"; sibling.father_id = "o"; sibling.generation = 1; var half := _sheep("h", SheepRecord.Sex.MALE); half.mother_id = "p"; half.father_id = "x"; half.generation = 1
	for sheep: SheepRecord in [parent, other, child, sibling, half]: assert(repo.add_sheep(sheep))
	var relationships := RelationshipService.new(repo); assert(relationships.classify(parent,parent) == RelationshipService.Classification.SELF); assert(relationships.classify(parent,child) == RelationshipService.Classification.PARENT_CHILD); assert(relationships.classify(child,sibling) == RelationshipService.Classification.FULL_SIBLING); assert(relationships.classify(child,half) == RelationshipService.Classification.HALF_SIBLING)
static func _test_breeding_birth_and_persistence() -> void:
	var repo := FlockRepository.new(); var female := _sheep("female", SheepRecord.Sex.FEMALE); var male := _sheep("male", SheepRecord.Sex.MALE); assert(repo.add_sheep(female) and repo.add_sheep(male)); var clock := GameClock.new(20000); var bred := BreedingService.new(repo).conceive("female", "male", clock.get_current_time(), 12345); assert(bred.success and female.pregnancy != null and repo.count() == 2); var due := female.pregnancy.due_game_minute; assert(not PregnancyService.new(repo).resolve_due_pregnancy(female, GameTime.new(due - 1)).success)
	var saved := FlockPersistence.to_json(repo, clock); var restored := FlockPersistence.from_json(saved); assert(restored != null and FlockPersistence.last_loaded_clock.get_total_minutes() == 20000); var restored_female := restored.get_sheep("female"); var birth := PregnancyService.new(restored).resolve_due_pregnancy(restored_female, GameTime.new(due)); assert(birth.success and birth.lambs.size() in [1,2,3] and restored_female.pregnancy == null); assert(not PregnancyService.new(restored).resolve_due_pregnancy(restored_female, GameTime.new(due + 1)).success); assert(restored_female.breeding_available_game_minute == due + 2 * 1440)
	assert(PregnancyService.select_litter_size(0.0) == 1 and PregnancyService.select_litter_size(0.6999) == 1 and PregnancyService.select_litter_size(0.70) == 2 and PregnancyService.select_litter_size(0.9499) == 2 and PregnancyService.select_litter_size(0.95) == 3)
	for lamb: SheepRecord in birth.lambs: assert(lamb.validate() and lamb.age_stage == SheepRecord.AgeStage.LAMB and lamb.birth_game_minute == due and not lamb.life_events.is_empty())
static func _test_wool_and_shearing() -> void:
	var repo := FlockRepository.new(); var sheep := _sheep("wool", SheepRecord.Sex.FEMALE); assert(repo.add_sheep(sheep)); var wool := WoolGrowthService.new(); wool.advance_wool_growth(sheep, LifecycleConfig.FULL_WOOL_GROWTH_DAYS * 1440 / 2); assert(is_equal_approx(sheep.wool_growth, 0.5)); wool.advance_wool_growth(sheep, 999999); assert(sheep.wool_growth == 1.0); var shear := ShearingService.new(repo); assert(shear.shear("wool", GameTime.new()).success and sheep.wool_growth == 0.0); sheep.wool_growth = 1.0; assert(shear.shear("wool", GameTime.new(1)).success); assert(SheepHistoryService.new(repo).get_events_by_type("wool", SheepLifeEvent.Type.FIRST_SHEAR).size() == 1); sheep.location = SheepRecord.Location.BARN_ARCHIVE; wool.advance_wool_growth(sheep, 999999); assert(sheep.wool_growth == 0.0)
static func _test_large_jump() -> void:
	var repo := FlockRepository.new(); var sheep := _sheep("jump", SheepRecord.Sex.FEMALE, SheepRecord.AgeStage.LAMB); assert(repo.add_sheep(sheep)); var clock := GameClock.new(); SimulationCoordinator.new().advance_simulation(repo, clock, 100 * 1440); assert(sheep.age_stage == SheepRecord.AgeStage.ELDER and sheep.location == SheepRecord.Location.ACTIVE_FLOCK and sheep.life_events.size() == 3)
static func _sheep(id: String, sex: SheepRecord.Sex, age: SheepRecord.AgeStage = SheepRecord.AgeStage.ADULT) -> SheepRecord:
	var sheep := SheepRecord.new(); sheep.sheep_id = id; sheep.sheep_name = id; sheep.sex = sex; sheep.age_stage = age; sheep.genome = SheepFactory.default_genome(); var rng := RandomNumberGenerator.new(); rng.seed = id.hash(); sheep.personality = PersonalityGenerator.generate_founder_personality(rng); return sheep
