class_name TestLifecycleSimulation
extends RefCounted

static func run() -> void:
	_test_time_and_age(); _test_relationships(); _test_breeding_birth_and_persistence(); _test_wool_intervals(); _test_shearing_statistics(); _test_load_authority()
static func _test_time_and_age() -> void:
	var clock := GameClock.new(); assert(clock.get_current_time().get_day() == 1); assert(not clock.advance_minutes(-1)); assert(clock.advance_days(1) and clock.get_total_minutes() == 1440 and clock.get_current_time().get_day() == 2); assert(clock.advance_hours(1) and clock.get_total_minutes() == 1500)
	var repository := FlockRepository.new(); var sheep := _sheep("age", SheepRecord.Sex.FEMALE, SheepRecord.AgeStage.LAMB); assert(repository.add_sheep(sheep)); var service := LifecycleService.new(repository)
	var boundaries := [[0,SheepRecord.AgeStage.LAMB],[7*1440-1,SheepRecord.AgeStage.LAMB],[7*1440,SheepRecord.AgeStage.JUVENILE],[14*1440-1,SheepRecord.AgeStage.JUVENILE],[14*1440,SheepRecord.AgeStage.ADULT],[90*1440-1,SheepRecord.AgeStage.ADULT],[90*1440,SheepRecord.AgeStage.ELDER]]
	for boundary: Array in boundaries: assert(service.resolve_age_stage(sheep, GameTime.new(boundary[0])) == boundary[1])
static func _test_relationships() -> void:
	var repo := FlockRepository.new(); var grandparent := _sheep("gp", SheepRecord.Sex.FEMALE); var parent := _sheep("p", SheepRecord.Sex.FEMALE); parent.mother_id = "gp"; parent.generation = 1; var other := _sheep("o", SheepRecord.Sex.MALE); var child := _sheep("c", SheepRecord.Sex.FEMALE); child.mother_id = "p"; child.father_id = "o"; child.generation = 2; var sibling := _sheep("s", SheepRecord.Sex.MALE); sibling.mother_id = "p"; sibling.father_id = "o"; sibling.generation = 2; var half := _sheep("h", SheepRecord.Sex.MALE); half.mother_id = "p"; half.father_id = "x"; half.generation = 2; var unrelated := _sheep("u", SheepRecord.Sex.MALE)
	for sheep: SheepRecord in [grandparent, parent, other, child, sibling, half, unrelated]: assert(repo.add_sheep(sheep))
	var relationships := RelationshipService.new(repo); assert(relationships.classify(parent,parent) == RelationshipService.Classification.SELF); assert(relationships.classify(parent,child) == RelationshipService.Classification.PARENT_CHILD); assert(relationships.classify(child,parent) == RelationshipService.Classification.PARENT_CHILD); assert(relationships.classify(grandparent,child) == RelationshipService.Classification.OTHER_RELATIVE); assert(relationships.classify(child,grandparent) == RelationshipService.Classification.OTHER_RELATIVE); assert(relationships.classify(child,sibling) == RelationshipService.Classification.FULL_SIBLING); assert(relationships.classify(child,half) == RelationshipService.Classification.HALF_SIBLING); assert(relationships.classify(child,unrelated) == RelationshipService.Classification.UNRELATED)
static func _test_breeding_birth_and_persistence() -> void:
	var repo := FlockRepository.new(); var female := _sheep("female", SheepRecord.Sex.FEMALE); female.birth_game_minute = -14 * 1440; var male := _sheep("male", SheepRecord.Sex.MALE); male.birth_game_minute = -14 * 1440; assert(repo.add_sheep(female) and repo.add_sheep(male)); var clock := GameClock.new(20000); var bred := BreedingService.new(repo).conceive("female", "male", clock.get_current_time(), 12345); assert(bred.success and female.pregnancy != null and repo.count() == 2); var due := female.pregnancy.due_game_minute; assert(not PregnancyService.new(repo).resolve_due_pregnancy(female, GameTime.new(due - 1)).success)
	assert(FlockPersistence.to_json(repo, null).is_empty() and "requires an authoritative GameClock" in FlockPersistence.last_error)
	var saved := FlockPersistence.to_json(repo, clock); var restored := FlockPersistence.from_json(saved); assert(restored != null and FlockPersistence.last_loaded_clock.get_total_minutes() == 20000); var restored_female := restored.get_sheep("female"); var birth := PregnancyService.new(restored).resolve_due_pregnancy(restored_female, GameTime.new(due)); assert(birth.success and birth.lambs.size() in [1,2,3] and restored_female.pregnancy == null); assert(not PregnancyService.new(restored).resolve_due_pregnancy(restored_female, GameTime.new(due + 1)).success); assert(restored_female.breeding_available_game_minute == due + 2 * 1440)
	assert(PregnancyService.select_litter_size(0.0) == 1 and PregnancyService.select_litter_size(0.6999) == 1 and PregnancyService.select_litter_size(0.70) == 2 and PregnancyService.select_litter_size(0.9499) == 2 and PregnancyService.select_litter_size(0.95) == 3)
	for lamb: SheepRecord in birth.lambs: assert(lamb.validate() and lamb.age_stage == SheepRecord.AgeStage.LAMB and lamb.birth_game_minute == due and not lamb.life_events.is_empty())
static func _test_wool_intervals() -> void:
	var repo := FlockRepository.new(); var sheep := _sheep("wool", SheepRecord.Sex.FEMALE, SheepRecord.AgeStage.LAMB); assert(repo.add_sheep(sheep)); var clock := GameClock.new(); var coordinator := SimulationCoordinator.new(); coordinator.advance_simulation(repo, clock, 7 * 1440); assert(sheep.age_stage == SheepRecord.AgeStage.JUVENILE and sheep.wool_growth == 0.0); coordinator.advance_simulation(repo, clock, 1440); assert(is_equal_approx(sheep.wool_growth, 0.2))
	var large_repo := FlockRepository.new(); var large := _sheep("large", SheepRecord.Sex.FEMALE, SheepRecord.AgeStage.LAMB); assert(large_repo.add_sheep(large)); SimulationCoordinator.new().advance_simulation(large_repo, GameClock.new(), 100 * 1440); assert(large.age_stage == SheepRecord.AgeStage.ELDER and large.wool_growth == 1.0 and large.life_events.size() == 3)
	var archived := _sheep("archive", SheepRecord.Sex.FEMALE, SheepRecord.AgeStage.LAMB); archived.location = SheepRecord.Location.BARN_ARCHIVE; var archive_repo := FlockRepository.new(); assert(archive_repo.add_sheep(archived)); SimulationCoordinator.new().advance_simulation(archive_repo, GameClock.new(), 100 * 1440); assert(archived.wool_growth == 0.0)
static func _test_shearing_statistics() -> void:
	var repo := FlockRepository.new(); var sheep := _sheep("shear", SheepRecord.Sex.FEMALE); assert(repo.add_sheep(sheep)); var stats := LifetimeStatisticsService.new(repo); assert(stats.get_statistics("shear").shearing_count == 0); var first := SheepLifeEvent.new(); first.event_type = SheepLifeEvent.Type.FIRST_SHEAR; assert(SheepHistoryService.new(repo).record_event("shear", first)); assert(stats.get_statistics("shear").shearing_count == 0)
	for count: int in 3:
		var event := SheepLifeEvent.new(); event.event_type = SheepLifeEvent.Type.SHEARED; assert(SheepHistoryService.new(repo).record_event("shear", event)); assert(stats.get_statistics("shear").shearing_count == count + 1)
static func _test_load_authority() -> void:
	var repo := FlockRepository.new(); var newborn := _sheep("newborn", SheepRecord.Sex.FEMALE); newborn.birth_game_minute = 100 * 1440; var old := _sheep("old", SheepRecord.Sex.MALE, SheepRecord.AgeStage.LAMB); old.birth_game_minute = 0; assert(repo.add_sheep(newborn) and repo.add_sheep(old)); var clock := GameClock.new(100 * 1440); var data := FlockPersistence.to_dictionary(repo, clock); data.sheep[0].age_stage = SheepRecord.AgeStage.ADULT; data.sheep[1].age_stage = SheepRecord.AgeStage.LAMB; var loaded := FlockPersistence.from_dictionary(data); assert(loaded.get_sheep("newborn").age_stage == SheepRecord.AgeStage.LAMB and loaded.get_sheep("old").age_stage == SheepRecord.AgeStage.ELDER); assert(not BreedingEligibilityService.new(loaded).is_individually_eligible(loaded.get_sheep("newborn"), clock.get_current_time())); assert(not WoolGrowthService.new().is_ready_to_shear(loaded.get_sheep("newborn")))
	var valid_repo := FlockRepository.new(); var mother := _sheep("mother", SheepRecord.Sex.FEMALE); mother.birth_game_minute = -14 * 1440; var father := _sheep("father", SheepRecord.Sex.MALE); father.birth_game_minute = -14 * 1440; assert(valid_repo.add_sheep(mother) and valid_repo.add_sheep(father)); assert(BreedingService.new(valid_repo).conceive("mother", "father", GameTime.new(), 7).success); var valid := FlockPersistence.to_dictionary(valid_repo, GameClock.new()); assert(FlockPersistence.from_dictionary(valid) != null); var missing := valid.duplicate(true); missing.sheep.remove_at(0); assert(FlockPersistence.from_dictionary(missing) == null and "pregnancy partner" in FlockPersistence.last_error); var self_reference := valid.duplicate(true); self_reference.sheep[1].pregnancy.other_parent_id = self_reference.sheep[1].sheep_id; assert(FlockPersistence.from_dictionary(self_reference) == null and "pregnancy partner" in FlockPersistence.last_error)
static func _sheep(id: String, sex: SheepRecord.Sex, age: SheepRecord.AgeStage = SheepRecord.AgeStage.ADULT) -> SheepRecord:
	var sheep := SheepRecord.new(); sheep.sheep_id = id; sheep.sheep_name = id; sheep.sex = sex; sheep.age_stage = age; sheep.genome = SheepFactory.default_genome(); var rng := RandomNumberGenerator.new(); rng.seed = id.hash(); sheep.personality = PersonalityGenerator.generate_founder_personality(rng); return sheep
