class_name HusbandryConfig
extends RefCounted

# Provisional Milestone 5 balance values. All care state is normalized [0, 1].
const FULL_TO_EMPTY_HUNGER_DAYS := 2.0
const FULL_TO_DIRTY_DAYS := 4.0
const BASE_FEED_AMOUNT := 0.45
const TREAT_FEED_AMOUNT := 0.20
const BASE_FEED_HAPPINESS_GAIN := 0.03
const TREAT_FEED_HAPPINESS_GAIN := 0.02
const BASE_FEED_BOND_GAIN := 0.01
const FAVORITE_HAPPINESS_BONUS := 0.08
const FAVORITE_BOND_BONUS := 0.03
const DISLIKED_HAPPINESS_MODIFIER := -0.01
const GREEDY_HAPPINESS_MULTIPLIER := 1.35
const CURIOUS_NOVEL_FOOD_BONUS := 0.02
const PET_HAPPINESS_GAIN := 0.08
const PET_BOND_GAIN := 0.04
const GROOM_CLEANLINESS_GAIN := 0.45
const GROOM_HAPPINESS_GAIN := 0.05
const GROOM_BOND_GAIN := 0.02
const WASH_CLEANLINESS_GAIN := 0.80
const WASH_HAPPINESS_MODIFIER := 0.01
const WASH_BOND_GAIN := 0.01
const LAMB_BOND_MULTIPLIER := 1.20
const ELDER_PET_BOND_MULTIPLIER := 1.10
const HAPPINESS_HUNGER_WEIGHT := 0.50
const HAPPINESS_CLEANLINESS_WEIGHT := 0.30
const HAPPINESS_BOND_WEIGHT := 0.20
const HAPPINESS_RESPONSE_PER_DAY := 0.35
const WOOL_CARE_MIN_MULTIPLIER := 0.50
const BREEDING_HAPPINESS_THRESHOLD := 0.40
const BREEDING_HUNGER_THRESHOLD := 0.40
const MOOD_CRITICAL_NEED_THRESHOLD := 0.25
const MOOD_HIGH_HAPPINESS := 0.75
const MOOD_HIGH_BOND := 0.65
const MOOD_LOW_HAPPINESS := 0.30
const MOOD_LOW_BOND := 0.20
